# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 956488d4c54fde33f0e044e1169e9ec5d349cc2a591367ce91c1de02581c0e05a91292d506e104f0e5c5b1ca9760104e05d0ab730766ac1d8e24ff7934848d04

test:
  secret_key_base: 2c2f8d26aa679bec4b4008f9f4ab06fcee60ebfbd568b25889a2e63d09bfbf3322add6280f02b774b3c059030b6faa7a91888d437ee913c6c03cbee5f5b9fe79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
